version: "3.5"

services:
  adminer:
    image: adminer
    container_name: ${APP_NAME}
    expose:
      - "8080"
    ports:
      - 8080:8080
    environment:
      VIRTUAL_HOST: ${NGINX_HOST}
      LETSENCRYPT_HOST: ${NGINX_HOST}
      LETSENCRYPT_EMAIL: ${NGINX_EMAIL}
      ADMINER_DEFAULT_SERVER: ${ADMINER_DEFAULT_SERVER}
    logging:
      options:
        max-size: "1m"

networks:
  default:
    external:
      name: nginx-proxy
